name: firebasestarter
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^1.0.7
  device_info: ^2.0.2
  firebase_analytics: ^8.1.0
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  firebase_crashlytics: ^2.0.4
  firebase_helpers: ^0.3.1
  firebase_messaging: ^10.0.0
  firebase_remote_config: ^0.10.0
  firebase_storage: ^8.1.0
  # flutter_auth_buttons: ^0.9.0
  flutter_form_builder: ^6.0.1
  flutter_riverpod: ^0.14.0+3
  flutter_svg: ^0.22.0
  # flutter_swiper: ^1.1.6
  google_fonts: ^2.1.0
  google_sign_in: ^5.0.4
  image_cropper: ^1.4.0
  image_picker: ^0.7.5+3
  intl: ^0.17.0
  package_info: ^2.0.2
  table_calendar: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0
  # flutter_automation: ^1.4.0
  # intl_translation: ^0.17.0
flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
